[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Solidity compiler settings
solc = "0.8.25"
via_ir = true

# Optimizer settings
optimizer = true
optimizer_runs = 200

# EVM settings
evm_version = "cancun"

# Formatter
fmt.line_length = 120
fmt.tab_width = 4
fmt.bracket_spacing = true

# Testing
fuzz.runs = 256
invariant.runs = 256

# Gas reporting
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
